import { Link } from 'react-router-dom'
import { useTheme } from '../contexts/ThemeContext'

interface BlogPost {
  id: string
  date: string
  title: string
  description: string
  tags: string[]
  author?: string
}

const Blog = () => {
  const { theme } = useTheme()
  
  const posts: BlogPost[] = [
    {
      id: 'building-ai-chatbot',
      date: 'March 20, 2025',
      title: 'Building and Deploying a Personal AI Chatbot',
      description: 'A comprehensive guide on creating a custom AI chatbot using modern technologies and deploying it on a personal website',
      tags: ['ai', 'typescript', 'react', 'openai', 'supabase'],
      author: 'Your Name'
    },
    {
      id: 'training-ai-agent-orbito',
      date: 'March 31, 2025',
      title: 'Training an AI Agent to Play Orbito',
      description: 'A deep dive into training a Deep Q-Network (DQN) agent to play Orbito, featuring prioritized experience replay and intrinsic rewards for exploration.',
      tags: ['AI', 'Reinforcement Learning', 'DQN', 'Game AI', 'Python'],
      author: 'Your Name'
    },
    {
      id: 'developer-productivity-setup',
      date: 'March 28, 2024',
      title: 'My Ultimate Developer Productivity Setup 2024',
      description: 'A detailed walkthrough of my development environment, productivity tools, and terminal configuration that supercharge my daily workflow',
      tags: ['productivity', 'tools', 'terminal', 'development'],
      author: 'Your Name'
    }
  ]

  return (
    <div className="min-h-screen p-8 pb-24">
      <div className="max-w-4xl mx-auto">
        <h1 className={`text-5xl font-bold ${theme === 'dark' ? 'text-white' : 'text-gray-900'} mb-4`}>Blog</h1>
        <p className={`${theme === 'dark' ? 'text-white' : 'text-gray-700'} mb-2`}>
          My thoughts on various topics. You can comment on my blog posts (Yes I got this function implemented)
        </p>
        <p className={`${theme === 'dark' ? 'text-white' : 'text-gray-700'} mb-8 underline`}>
          <strong>Warning:</strong> All of my current blog are generated by AI. Have not got around to write any blog posts yet.
        </p>

        <div className="space-y-6">
          {posts.map((post) => (
            <div 
              key={post.id} 
              className={`bg-[#1a1a1a] dark:bg-[#1a1a1a] light:bg-white border border-gray-800 dark:border-gray-800 light:border-gray-300 rounded-lg p-6 hover:border-gray-700 dark:hover:border-gray-700 light:hover:border-gray-400 transition-all hover:shadow-lg`}
            >
              <div className="flex justify-between items-start mb-3">
                <span className={`${theme === 'dark' ? 'text-gray-400' : 'text-gray-600'} text-sm`}>{post.date}</span>
                <span className={`${theme === 'dark' ? 'text-gray-400' : 'text-gray-600'} text-sm`}>
                  {post.author ? `By ${post.author}` : 'By Your Name'}
                </span>
              </div>
              <h2 className={`text-2xl font-bold ${theme === 'dark' ? 'text-white' : 'text-gray-900'} mb-3`}>
                {post.title}
              </h2>
              <p className={`${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'} mb-4`}>
                {post.description}
              </p>
              <div className="flex flex-wrap gap-2 mb-4">
                {post.tags.map((tag, tagIndex) => (
                  <span
                    key={tagIndex}
                    className={`px-3 py-1 rounded-full text-sm font-medium transition-colors cursor-pointer ${
                      theme === 'dark' 
                        ? 'bg-gray-800 text-gray-300 hover:bg-gray-700 hover:text-white' 
                        : 'bg-gray-100 text-gray-700 hover:bg-gray-200 hover:text-gray-900'
                    }`}
                  >
                    {tag}
                  </span>
                ))}
              </div>
              <Link 
                to={`/blog/${post.id}`} 
                className={`inline-flex items-center ${theme === 'dark' ? 'text-white hover:text-blue-400' : 'text-gray-900 hover:text-blue-600'} transition-colors`}
              >
                read more &gt;
              </Link>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

export default Blog
