import React from 'react'

interface BlogPost {
  date: string
  title: string
  description: string
  tags: string[]
}

const Blog = () => {
  const posts: BlogPost[] = [
    {
      date: 'March 20, 2025',
      title: 'Blog Post Title 1',
      description: 'Description of your blog post goes here.',
      tags: ['tag1', 'tag2', 'tag3']
    },
    {
      date: 'March 31, 2025',
      title: 'Blog Post Title 2',
      description: 'Another blog post description.',
      tags: ['tag1', 'tag2']
    }
  ]

  return (
    <div className="min-h-screen p-8 pb-24">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-5xl font-bold text-white mb-4">Blog</h1>
        <p className="text-white mb-2">
          My thoughts on various topics. You can comment on my blog posts (Yes I got this function implemented)
        </p>
        <p className="text-white mb-8 underline">
          <strong>Warning:</strong> All of my current blog are generated by AI. Have not got around to write any blog posts yet.
        </p>

        <div className="space-y-6">
          {posts.map((post, index) => (
            <div key={index} className="bg-[#1a1a1a] border border-gray-800 rounded-lg p-6 hover:border-gray-700 transition-colors">
              <div className="flex justify-between items-start mb-3">
                <span className="text-gray-400 text-sm">{post.date}</span>
                <span className="text-gray-400 text-sm">By Your Name</span>
              </div>
              <h2 className="text-2xl font-bold text-white mb-3">{post.title}</h2>
              <p className="text-gray-300 mb-4">{post.description}</p>
              <div className="flex flex-wrap gap-2 mb-4">
                {post.tags.map((tag, tagIndex) => (
                  <span
                    key={tagIndex}
                    className="px-3 py-1 bg-gray-800 text-white rounded-full text-sm"
                  >
                    {tag}
                  </span>
                ))}
              </div>
              <a href="#" className="text-white hover:text-blue-400 transition-colors">
                read more &gt;
              </a>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

export default Blog

